const fs = require('node:fs')
const path = require('node:path')

/**
 * Prisma Client v7 generates `node_modules/.prisma/client/default.js` which may contain:
 *   module.exports = { ...require('#main-entry-point') }
 *
 * In some Windows + Node loader setups, `require('#main-entry-point')` fails.
 * We patch it to a stable relative require to `./index.js`.
 *
 * This file is re-generated by `prisma generate`, so we run this patch right after generate.
 */

const target = path.join(process.cwd(), 'node_modules', '.prisma', 'client', 'default.js')

if (!fs.existsSync(target)) {
  console.warn(`[prisma patch] Skip: not found: ${target}`)
  process.exit(0)
}

const before = fs.readFileSync(target, 'utf8')
const from = "require('#main-entry-point')"
const to = "require('./index.js')"

if (!before.includes(from)) {
  console.log('[prisma patch] Skip: pattern not found (already patched or different client).')
  process.exit(0)
}

const after = before.replace(from, to)
fs.writeFileSync(target, after, 'utf8')
console.log('[prisma patch] Patched node_modules/.prisma/client/default.js')

